server:
  port: 8080
  compression:
    enabled: true # Whether response compression is enabled.
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
    min-response-size: 1024 # Minimum "Content-length" value that is required for compression to be performed.
  undertow:
    threads:
      worker: 64
      io: 4